export const FETCH_CURRENCIES_START = 'FETCH_CURRENCIES_START';
export const FETCH_CURRENCIES_SUCCESS = 'FETCH_CURRENCIES_SUCCESS';
export const FETCH_LIVE_START = 'FETCH_LIVE_START';
export const FETCH_LIVE_SUCCESS = 'FETCH_LIVE_SUCCESS';
export const FETCH_CONVERT_START = 'FETCH_CONVERT_START';
export const FETCH_CONVERT_SUCCESS = 'FETCH_CONVERT_SUCCESS';
export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';