export const FETCH_CURRENCIES_START = 'FETCH_CURRENCIES_START';
export const FETCH_CURRENCIES_SUCCESS = 'FETCH_CURRENCIES_SUCCESS';
export const SEARCH_CURRENCY_BY_NAME = 'SEARCH_CURRENCY_BY_NAME';
export const SET_BACKUP_CURRENCIES = 'SET_BACKUP_CURRENCIES';
export const SET_PRIMARY_CURRENCY = 'SET_PRIMARY_CURRENCY';
